# Generated by Django 5.2.3 on 2026-03-31 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuturesContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("root_symbol", models.CharField(db_index=True, max_length=10)),
                ("month_code", models.CharField(max_length=1)),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="price",
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="close",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="high",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="low",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="open",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="volume",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="stock",
            name="symbol",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name="FuturesPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "contracts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="base.futurescontract",
                    ),
                ),
            ],
        ),
    ]
