# Generated by Django 6.0.3 on 2026-04-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_futurescontract_remove_pricehistory_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='futurespricehistory',
            name='close_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futurespricehistory',
            name='high_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futurespricehistory',
            name='low_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futurespricehistory',
            name='open_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futurespricehistory',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='futurespricehistory',
            constraint=models.UniqueConstraint(fields=('contracts', 'date'), name='unique_contract_date'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_date'),
        ),
    ]
